### ISSUE TITLE
Failed to recognize group to respawn once it has died

### ISSUE THREAD

**Issue by 111LuisPa** [birgersp/dcs-gws#125]
hola,  desde la ultima actualización de DCS el jueves 17/03//2022 he notado que una vez que uno de los grupos muere no es capaz de volver a sacarlo, y genera un error como si no encontrase al grupo inicial.
Se sigue trabajando en este proyecto?
Gracias de ante mano, no soy programador, pero tenemos hecha una campaña dinámica de DCS en el E111 Español, con este Script y nos gusta mucho como funciona y no nos gustaría perderlo.

**Comment by birgersp** [comment]
Hello, please submit your issue in English.

**Comment by 111LuisPa** [comment]
hello, since the last DCS update on Thursday 03/17/2022 noticed that once one of the groups dies it is not able to get it back, and it generates an error as if it did not find the initial group.
Are you still working on this project?
Thanks in advance, I am not a programmer, but we have made a dynamic DCS campaign in Spanish E111, with this Script and we really like how it works and we would not like to lose it.

**Comment by 111LuisPa** [comment]
if you create a simple example, two groups one in front of the other with for example a maximum of 10 spawn, per group, as soon as one of the two dies, it gives an error that it does not locate the group (dead) to spawn again

**Comment by birgersp** [comment]
Thanks. I just released a patched version, but I didn't have time to test this more thorough. This problem might appear elsewhere in the script, I'll try to fix more errors when they appear. Please try v 1.20

**Comment by 111LuisPa** [comment]
It has already been solved, thank you very much, and I encourage you to continue with the project.
